project:
  type: website
  output-dir: docs

website:
  title: "Zach Thomson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - The_Guardian_Text_Analysis.qmd
      - href: choropleth_maps.qmd
        text: Hospital Spening Choropleth Maps
      
        

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

